language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./tools/setdebugtype.sh
  - chmod a+x ./tools/build.sh
  - ./tools/setdebugtype.sh
script:
  - ./tools/build.sh --quiet verify
